spring.application.name=demo

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


dynamic.endpoint.request.base-package=com.example.demo.request
dynamic.endpoint.dto.base-package=com.example.demo.dto
